INSERT INTO UserProfiles (Email, Password, FirstName, LastName, ProfileType, loggedIn)
VALUES
('user1@example.com', 'password1', 'John', 'Doe', 'USER', 0),
('user2@example.com', 'password2', 'Jane', 'Smith', 'USER', 0),
('admin@example.com', 'adminpassword', 'Admin', 'User', 'ADMIN', 0),
('user3@example.com', 'password3', 'Michael', 'Johnson', 'USER', 0),
('user4@example.com', 'password4', 'Emily', 'Davis', 'USER', 0),
('user5@example.com', 'password5', 'David', 'Brown', 'USER', 0),
('user6@example.com', 'password6', 'Sarah', 'Wilson', 'USER', 0),
('user7@example.com', 'password7', 'Daniel', 'Martinez', 'USER', 0),
('user8@example.com', 'password8', 'Jennifer', 'Taylor', 'USER', 0),
('user9@example.com', 'password9', 'Jessica', 'Anderson', 'USER', 0),
('user10@example.com', 'password10', 'Matthew', 'Thomas', 'USER', 0),
('user11@example.com', 'password11', 'Andrew', 'Jackson', 'USER', 0),
('user12@example.com', 'password12', 'Michelle', 'Lee', 'USER', 0),
('user13@example.com', 'password13', 'Christopher', 'Harris', 'USER', 0),
('user14@example.com', 'password14', 'Amanda', 'Clark', 'USER', 0);

SELECT * from userprofiles;

INSERT INTO ProductListings (SellerID, Title, Price, Description, Category, Image, Status)
VALUES
(1, 'T-shirt', 19.99, 'Plain white T-shirt', 'CLOTHES', 'https://example.com/tshirt.jpg', 'ACTIVE'),
(2, 'Smartphone', 499.99, 'Latest model smartphone', 'ELECTRONICS', 'https://example.com/smartphone.jpg', 'ACTIVE'),
(1, 'Coffee Table', 149.99, 'Wooden coffee table', 'FURNITURE', 'https://example.com/coffeetable.jpg', 'SOLD'),
(1, 'Running Shoes', 79.99, 'High-performance running shoes', 'CLOTHES', 'https://example.com/runningshoes.jpg', 'ACTIVE'),
(1, 'Laptop', 899.99, 'Powerful laptop for professionals', 'ELECTRONICS', 'https://example.com/laptop.jpg', 'ACTIVE'),
(1, 'Sofa', 499.99, 'Comfortable sofa for your living room', 'FURNITURE', 'https://example.com/sofa.jpg', 'ACTIVE'),
(2, 'Lipstick', 14.99, 'Long-lasting lipstick in various shades', 'BEAUTY', 'https://example.com/lipstick.jpg', 'ACTIVE'),
(2, 'DVD Player', 49.99, 'Compact DVD player with HDMI output', 'ENTERTAINMENT', 'https://example.com/dvdplayer.jpg', 'ACTIVE'),
(2, 'Sweater', 39.99, 'Warm and cozy sweater for winter', 'CLOTHES', 'https://example.com/sweater.jpg', 'ACTIVE'),
(3, 'Headphones', 99.99, 'Noise-canceling headphones with Bluetooth connectivity', 'ELECTRONICS', 'https://example.com/headphones.jpg', 'ACTIVE'),
(4, 'Dresser', 299.99, 'Spacious dresser with multiple drawers', 'FURNITURE', 'https://example.com/dresser.jpg', 'ACTIVE'),
(1, 'Perfume', 29.99, 'Elegant perfume with a floral scent', 'BEAUTY', 'https://example.com/perfume.jpg', 'SOLD'),
(6, 'Gaming Console', 399.99, 'Next-gen gaming console with 4K graphics', 'ENTERTAINMENT', 'https://example.com/gamingconsole.jpg', 'ACTIVE'),
(3, 'Sunglasses', 49.99, 'Stylish sunglasses with UV protection', 'CLOTHES', 'https://example.com/sunglasses.jpg', 'INACTIVE'),
(4, 'Desk Chair', 79.99, 'Ergonomic desk chair for long hours of work', 'FURNITURE', 'https://example.com/deskchair.jpg', 'INACTIVE'),
(5, 'Earrings', 19.99, 'Fashionable earrings in various designs', 'BEAUTY', 'https://example.com/earrings.jpg', 'INACTIVE'),
(6, 'Board Game', 29.99, 'Classic board game for family fun', 'ENTERTAINMENT', 'https://example.com/boardgame.jpg', 'INACTIVE'),
(7, 'Jeans', 59.99, 'Premium denim jeans for casual wear', 'CLOTHES', 'https://example.com/jeans.jpg', 'SOLD'),
(8, 'TV Stand', 199.99, 'Modern TV stand with storage compartments', 'FURNITURE', 'https://example.com/tvstand.jpg', 'SOLD'),
(9, 'Foundation', 24.99, 'Matte finish foundation for all-day wear', 'BEAUTY', 'https://example.com/foundation.jpg', 'SOLD'),
(10, 'Bluetooth Speaker', 79.99, 'Portable Bluetooth speaker with long battery life', 'ENTERTAINMENT', 'https://example.com/bluetoothspeaker.jpg', 'SOLD'),
(7, 'Hoodie', 39.99, 'Comfortable hoodie for everyday use', 'CLOTHES', 'https://example.com/hoodie.jpg', 'ACTIVE'),
(8, 'Bookshelf', 149.99, 'Sturdy bookshelf for organizing your books', 'FURNITURE', 'https://example.com/bookshelf.jpg', 'ACTIVE'),
(9, 'Mascara', 12.99, 'Volumizing mascara for fuller lashes', 'BEAUTY', 'https://example.com/mascara.jpg', 'ACTIVE'),
(10, 'Movie Box Set', 69.99, 'Complete box set of popular movies', 'ENTERTAINMENT', 'https://example.com/movieboxset.jpg', 'ACTIVE'),
(11, 'Sweatpants', 29.99, 'Cozy sweatpants for lounging at home', 'CLOTHES', 'https://example.com/sweatpants.jpg', 'INACTIVE'),
(12, 'Coffee Maker', 59.99, 'Drip coffee maker with programmable features', 'FURNITURE', 'https://example.com/coffeemaker.jpg', 'INACTIVE'),
(13, 'Eyeliner', 9.99, 'Waterproof eyeliner for precise application', 'BEAUTY', 'https://example.com/eyeliner.jpg', 'INACTIVE'),
(14, 'Karaoke Machine', 129.99, 'Karaoke machine with built-in microphone', 'ENTERTAINMENT', 'https://example.com/karaoke.jpg', 'SOLD'),
(1, 'Backpack', 29.99, 'Durable backpack for everyday use', 'CLOTHES', 'https://example.com/backpack.jpg', 'SOLD'),
(2, 'Digital Camera', 299.99, 'High-resolution digital camera for photography enthusiasts', 'ELECTRONICS', 'https://example.com/camera.jpg', 'SOLD'),
(3, 'Dining Table', 399.99, 'Elegant dining table for family gatherings', 'FURNITURE', 'https://example.com/diningtable.jpg', 'SOLD'),
(4, 'Lip Gloss Set', 19.99, 'Set of lip glosses in various shades', 'BEAUTY', 'https://example.com/lipgloss.jpg', 'SOLD'),
(5, 'Home Theater System', 599.99, 'Complete home theater system for immersive entertainment', 'ENTERTAINMENT', 'https://example.com/hometheater.jpg', 'SOLD'),
(6, 'Winter Jacket', 79.99, 'Insulated winter jacket for cold weather', 'CLOTHES', 'https://example.com/winterjacket.jpg', 'SOLD'),
(7, 'Coffee Table', 149.99, 'Modern coffee table with a glass top', 'FURNITURE', 'https://example.com/coffeetable2.jpg', 'SOLD'),
(8, 'Perfume Set', 49.99, 'Collection of luxury perfumes for special occasions', 'BEAUTY', 'https://example.com/perfumeset.jpg', 'SOLD'),
(9, 'Gaming Chair', 199.99, 'Comfortable gaming chair with adjustable armrests', 'ENTERTAINMENT', 'https://example.com/gamingchair.jpg', 'SOLD'),
(10, 'Trench Coat', 89.99, 'Classic trench coat for a sophisticated look', 'CLOTHES', 'https://example.com/trenchcoat.jpg', 'SOLD'),
(11, 'Bed Frame', 249.99, 'Stylish bed frame for a comfortable night\'s sleep', 'FURNITURE', 'https://example.com/bedframe.jpg', 'SOLD'),
(12, 'Eyeshadow Palette', 39.99, 'Palette of eyeshadows in various colors and finishes', 'BEAUTY', 'https://example.com/eyeshadowpalette.jpg', 'SOLD'),
(13, 'Wireless Headphones', 149.99, 'Wireless headphones with long battery life', 'ELECTRONICS', 'https://example.com/wirelessheadphones.jpg', 'SOLD'),
(14, 'Smartwatch', 199.99, 'Advanced smartwatch with fitness tracking features', 'ELECTRONICS', 'https://example.com/smartwatch.jpg', 'SOLD'),
(1, 'Sweatshirt', 34.99, 'Cozy sweatshirt for chilly days', 'CLOTHES', 'https://example.com/sweatshirt2.jpg', 'SOLD'),
(2, 'Desk Lamp', 19.99, 'Adjustable desk lamp for study or work', 'FURNITURE', 'https://example.com/desklamp.jpg', 'SOLD'),
(3, 'Facial Cleanser', 9.99, 'Gentle facial cleanser for daily skincare routine', 'BEAUTY', 'https://example.com/facialcleanser.jpg', 'SOLD'),
(4, 'Bluetooth Earbuds', 79.99, 'Wireless earbuds with noise cancellation technology', 'ELECTRONICS', 'https://example.com/bluetoothearbuds.jpg', 'SOLD'),
(5, 'Artificial Christmas Tree', 99.99, 'Festive artificial Christmas tree for holiday decoration', 'ENTERTAINMENT', 'https://example.com/christmastree.jpg', 'SOLD'),
(6, 'Hiking Boots', 129.99, 'Sturdy hiking boots for outdoor adventures', 'CLOTHES', 'https://example.com/hikingboots.jpg', 'SOLD');

SELECT * from ProductListings;